name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main       

jobs:
  eb-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python & EB CLI
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install --no-cache-dir awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWSACCESSKEY }}
          aws-secret-access-key: ${{ secrets.AWSSACCESSKEY }}
          aws-region:            ${{ secrets.AWSREGION }}

      - name: Deploy to Elastic Beanstalk
        # assumes you've committed your .elasticbeanstalk/config.yml
        run: eb deploy ${{ secrets.EBENVNAME }} --verbose
